
#ifndef DISPLAY_CONTENT_DESIGN
#define DISPLAY_CONTENT_DESIGN

#define VAR_INPUT_BANNER	"=== INPUT VARIABLES ==="

#define POSITION_INPUT		"INPUT POSITION : "
#define HEIGHT_INPUT		"INPUT HEIGHT : "
#define WIDTH_INPUT			"INPUT WIDTH  : "
#define MINES_INPUT			"INPUT MINES  : "

#endif