
#ifndef GAME_SYMBOL_DEFINITIONS
#define GAME_SYMBOL_DEFINITIONS

#define THREAT_SYMBOL 	'@'
#define EMPTY_SYMBOL  	'.'
#define SQUARE_SYMBOL 	'+'

#define THREAT_COLOR	RED_COLOR
#define EMPTY_COLOR		WHITE_COLOR
#define SQUARE_COLOR 	WHITE_COLOR

#define INDEX_COLOR		CYAN_COLOR
#define TEXT_COLOR		WHITE_COLOR

#define BEFORE_INP		TEXT_COLOR
#define AFTER_INP		GREEN_COLOR

#define ONE_COLOR 		GREEN_COLOR
#define TWO_COLOR		CYAN_COLOR
#define THREE_COLOR		BLUE_COLOR
#define FOUR_COLOR		BLUE_COLOR
#define FIVE_COLOR		PURPLE_COLOR
#define SIX_COLOR		PURPLE_COLOR
#define SEVEN_COLOR		RED_COLOR
#define EIGHT_COLOR		RED_COLOR

#define ERROR_TEXT		"ERROR"
#define ERROR_SYMBOL	'X'
#define ERROR_COLOR		RED_COLOR

#endif