
#ifndef GAME_SYMBOL_DEFINITIONS
#define GAME_SYMBOL_DEFINITIONS

#define THREAT_SYMBOL '@'
#define EMPTY_SYMBOL  '.'
#define SQUARE_SYMBOL '+'

#define THREAT_COLOR	RED_COLOR
#define EMPTY_COLOR		WHITE_COLOR
#define SQUARE_COLOR 	WHITE_COLOR

#define INDEX_COLOR		CYAN_COLOR
#define TEXT_COLOR		BLUE_COLOR

#define BEFORE_INP		RED_COLOR
#define AFTER_INP		GREEN_COLOR

#define ONE_COLOR 		GREEN_COLOR
#define TWO_COLOR		GREEN_COLOR
#define THREE_COLOR		GREEN_COLOR
#define FOUR_COLOR		GREEN_COLOR
#define FIVE_COLOR		GREEN_COLOR
#define SIX_COLOR		GREEN_COLOR
#define SEVEN_COLOR		GREEN_COLOR
#define EIGHT_COLOR		GREEN_COLOR

#endif